
rocketmq:
#  name-server: localhost:9876
  name-server: 172.16.4.101:9876
  consumer:
    access-key: admin
    secret-key: 123456
  producer:
    access-key: admin
    secret-key: 123456
#  consumer:
#  producer:
#    group: rpsm-producer-logout-group
