
server:
  port: 10000

spring:
  cloud:
#    inetutils:
#      preferred-networks: 172.16.69.41 #,192.168
    sentinel:
      transport:
        port: 8719
        dashboard: 172.16.5.1:8900
        client-ip: 172.16.69.41




