
server:
  port: 10001

spring:
  cloud:
#    inetutils:
#      preferred-networks: 172.16.69.41 #,192.168
    sentinel:
      transport:
        port: 8720
        # 这个就是Sentinel-dashborad端口
        dashboard: 172.16.5.1:10010
#        dashboard: 172.16.5.1:8900
        client-ip: 172.16.69.41




